<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>$(ModIdentifier).Tests</AssemblyName>
    <RootNamespace>$(ModIdentifier).Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/$(ModIdentifier).Core/$(ModIdentifier).Core.csproj" />
  </ItemGroup>
</Project>
