<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>$(ModIdentifier).Tests</AssemblyName>
    <RootNamespace>$(ModIdentifier).Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/$(ModIdentifier).Core/$(ModIdentifier).Core.csproj" />
    <None Include="../fixtures/path_v2-prefab.json" Link="fixtures/path_v2-prefab.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../fixtures/key-hints-ui.json" Link="fixtures/key-hints-ui.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
